version: "3.3"

services:
  buyer-api:
    image: 192.168.124.9:5000/buyer-api:4.2.5
    container_name: buyer-api
    restart: always
    ports:
      - "9112:9112"
    volumes:
      - /home/data/programming/crbz/runapi/backend/logs:/data/crbz/logs
      - /home/data/programming/cert/wechatcert/xbm:/data/crbz/cert/wechatcert/xbm
      - /home/data/programming/cert/alipaycert/xbm/webapp:/data/crbz/cert/alipay/xbm/webapp
      - /home/data/programming/cert/alipaycert/xbm/basicapp:/data/crbz/cert/alipay/xbm/basicapp

  seller-api:
    image: 192.168.124.9:5000/seller-api:4.2.5
    container_name: seller-api
    restart: always
    ports:
      - "9117:9117"
    volumes:
      - /home/data/programming/crbz/runapi/backend/logs:/data/crbz/logs
      - /home/data/programming/cert/wechatcert/xbm:/data/crbz/cert/wechatcert/xbm

  manager-api:
    image: 192.168.124.9:5000/manager-api:4.2.5
    container_name: manager-api
    restart: always
    ports:
      - "9116:9116"
    volumes:
      - /home/data/programming/crbz/runapi/backend/logs:/data/crbz/logs
      - /home/data/programming/cert/wechatcert/xbm:/data/crbz/cert/wechatcert/xbm

  common-api:
    image: 192.168.124.9:5000/common-api:4.2.5
    container_name: common-api
    restart: always
    ports:
      - "9113:9113"
    volumes:
      - /home/data/programming/crbz/runapi/backend/logs:/data/crbz/logs
      - /home/data/programming/cert/wechatcert/xbm:/data/crbz/cert/wechatcert/xbm

  im-api:
    image: 192.168.124.9:5000/im-api:4.2.5
    container_name: im-api
    restart: always
    ports:
      - "9115:9115"
    volumes:
      - /home/data/programming/crbz/runapi/backend/logs:/data/crbz/logs
      - /home/data/programming/cert/wechatcert/xbm:/data/crbz/cert/wechatcert/xbm

  consumer:
    image: 192.168.124.9:5000/consumer:4.2.5
    container_name: consumer
    restart: always
    ports:
      - "9114:9114"
      - "8891:8891"
    volumes:
      - /home/data/programming/crbz/runapi/backend/logs:/data/crbz/logs
      - /home/data/programming/cert/wechatcert/xbm:/data/crbz/cert/wechatcert/xbm

  zbbb:
    image: 192.168.124.9:5000/zbbb:4.2.5
    container_name: zbbb
    restart: always
    ports:
      - "9118:9118"
    volumes:
      - /home/data/programming/crbz/runapi/backend/logs:/data/crbz/logs
      - /home/data/programming/cert/wechatcert/xbm:/data/crbz/cert/wechatcert/xbm

  jhkjgateway:
    image: 192.168.124.9:5000/jhkjgateway:4.2.5
    container_name: jhkjgateway
    restart: always
    ports:
      - "9111:9111"
    volumes:
      - /home/data/programming/crbz/runapi/backend/logs:/data/crbz/logs
      - /home/data/programming/cert/wechatcert/xbm:/data/crbz/cert/wechatcert/xbm

  admin:
    image: 192.168.124.9:5000/admin:4.2.5
    container_name: admin
    restart: always
    ports:
      - "9110:9110"
    volumes:
      - /home/data/programming/crbz/runapi/backend/logs:/data/crbz/logs
      - /home/data/programming/cert/wechatcert/xbm:/data/crbz/cert/wechatcert/xbm

