server:
  port: 8012

spring:
  mail:
#    host: smtp.qq.com #发送邮件服务器
    host: smtp.exmail.qq.com #发送邮件服务器
#    username: 1097951193@qq.com #QQ邮箱
    username: zhangjian@coshine.com
    password: Mts640102
#    password: djzfnzpkvvyqbacd #客户端授权码
    protocol: smtp #发送邮件协议
    properties.mail.smtp.auth: true
    properties.mail.smtp.port: 465 #端口号465或587
    properties.mail.display.sendmail: Javen #可以任意
    properties.mail.display.sendname: Spring Boot Guide Email #可以任意
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: UTF-8
    to1: 1097951193@qq.com
    to2: 18186854165@163.com
    to3: lixia@coshine.com
    to4: xiaoyq@coshine.com
    nickname: 张建


  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://192.168.2.200:3306/ssm_db?serverTimezone=UTC
      url: jdbc:mysql://192.168.2.180:3306/zbforcoshine?serverTimezone=UTC
      username:  zjzj
      password: 640102

mybatis-plus:
  global-config:
    db-config:
      table-prefix: tbl_
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml



