server:
  port: 9111
spring:
  cloud:
    gateway:
      routes:
        - id: zjmall-im
          uri: http://192.168.124.11:9115
          predicates:
            - Path=/im/**
        - id: zjmall-imws
          uri: ws://192.168.124.11:9115
          predicates:
            - Path=/crbz/**
        - id: zjmall-buyer
          uri: http://192.168.124.11:9112
          predicates:
            - Path=/buyer/**
        - id: zjmall-common
          uri: http://192.168.124.11:9113
          predicates:
            - Path=/common/**
        - id: zjmall-manager
          uri: http://192.168.124.11:9116
          predicates:
            - Path=/manager/**
        - id: zjmall-store
          uri: http://192.168.124.11:9117
          predicates:
            - Path=/store/**

        #周报开始
        - id: zjmall-ZBBBBB
          uri: http://192.168.124.11:9118
          predicates:
            - Path=/pages/**
        - id: zjmall-ZB
          uri: http://192.168.124.11:9118
          predicates:
            - Path=/zbfc/**
        #周报结束







