server:
  port: 9111
spring:
  cloud:
    gateway:
      routes:
        - id: zjmall-im
          uri: http://localhost:9115
          predicates:
            - Path=/im/**
        - id: zjmall-imws
          uri: ws://localhost:9115
          predicates:
            - Path=/lili/**
        #        - id: zjmall-impage
        #          uri: http://localhost:10004
        #          predicates:
        #            - Path=/message/**
        - id: zjmall-buyer
          uri: http://localhost:9112
          predicates:
            - Path=/buyer/**
        - id: zjmall-common
          uri: http://localhost:9113
          predicates:
            - Path=/common/**
        - id: zjmall-manager
          uri: http://localhost:9116
          predicates:
            - Path=/manager/**
        - id: zjmall-store
          uri: http://localhost:9117
          predicates:
            - Path=/store/**

        #周报开始
        - id: zjmall-ZBBBBB
          uri: http://localhost:9118
          predicates:
            - Path=/pages/**
        - id: zjmall-ZB
          uri: http://localhost:9118
          predicates:
            - Path=/zbfc/**
        #周报结束







