server:
  port: 9111
spring:
#  application:
#    name: zjmall-gateway
  cloud:
    gateway:
      #      globalcors:
      #        corsConfigurations:
      #          '[/**]':
      #            allowCredentials: true
      #            allowedHeaders: '*'
      #            allowedMethods: '*'
      #            allowedOriginPatterns: '*'
      routes:
        - id: zjmall-buyer
          uri: http://localhost:8859
          predicates:
            - Path=/buyer/**
        - id: zjmall-common
          uri: http://localhost:8890
          predicates:
            - Path=/common/**
        - id: zjmall-manager
          uri: http://localhost:8866
          predicates:
            - Path=/manager/**
        - id: zjmall-store
          uri: http://localhost:8855
          predicates:
            - Path=/store/**
              #西部梦start
        - id: zhou-xbm
          uri: http://localhost:9211
          predicates:
            - Path=/**
          filters:
            - PrefixPath=/im/**
            - PrefixPath=/common/**
            - PrefixPath=/store/**
            - PrefixPath=/manager/**
            - PrefixPath=/buyer/**
            - PrefixPath=/zbfc/**
        - id: zhou-xbm-page
          uri: http://localhost:3000
          predicates:
            - Host=aqewqv.natappfree.cc
          #西部梦结束







