server:
  port: 9111
spring:
  application:
    name: zjmall-gateway
  cloud:
    gateway:
      #      globalcors:
      #        corsConfigurations:
      #          '[/**]':
      #            allowCredentials: true
      #            allowedHeaders: '*'
      #            allowedMethods: '*'
      #            allowedOriginPatterns: '*'
      routes:
        - id: zjmall-buyer
          uri: http://localhost:8888
          predicates:
            - Path=/buyer/**
        - id: zjmall-common
          uri: http://localhost:8890
          predicates:
            - Path=/common/**
        - id: zjmall-manager
          uri: http://localhost:8866
          predicates:
            - Path=/manager/**
        - id: zjmall-store
          uri: http://localhost:8855
          predicates:
            - Path=/store/**
        - id: zjmall-nginx-buyer
          uri: http://localhost:11000
          predicates:
            - Host=zjmallbuyer.yqswgjz.mynatapp.cc
        - id: zjmall-nginx-buyerH5
          uri: http://localhost:8869
          predicates:
            - Host=yqswgjz.mynatapp.cc
        - id: zjmall-nginx-seller
          uri: http://localhost:10002
          predicates:
            - Host=seller.yqswgjz.mynatapp.cc
        - id: zjmall-nginx-manager
          uri: http://localhost:10003
          predicates:
            #            - Host=**.manager,manager
            - Host=manager.yqswgjz.mynatapp.cc
  #周报开始
        - id: zjmall-ZBBBBB
          uri: http://localhost:8012
          predicates:
            - Path=/pages/**
        - id: zjmall-ZBBB
          uri: http://localhost:8012
          predicates:
            - Host=zb.yqswgjz.mynatapp.cc
        - id: zjmall-ZB
          uri: http://localhost:8012
          predicates:
            - Path=/zbfc/**
  #周报结束
        - id: zjmall-chatwithme
          uri: http://localhost:8899
          predicates:
            - Host=chat.yqswgjz.mynatapp.cc
        - id: zjmall-pay
          uri: http://localhost:8892
          predicates:
            - Host=zjpay.yqswgjz.mynatapp.cc
        - id: zjpay-payurl
          uri: http://localhost:8892
          predicates:
            - Path=/pay/**
            - Path=/page/**
            - Path=/wechat/**
            - Path=/success
            - Path=/500
            - Path=/error
            - Path=/thanks





